FROM eclipse-mosquitto:latest

# Copy configuration and password to config folder
COPY ./docker/mosquitto_broker/config /mosquitto/config
COPY ./docker/mosquitto_broker/.keys/passwords.txt /mosquitto/config/passwords.txt

# Expose port 8883
EXPOSE 8883

# Set up logs folder
RUN mkdir -p /mosquitto/log \
    && touch /mosquitto/log/mosquitto.log \
    && chown mosquitto:mosquitto /mosquitto/log \
    && chmod 777 -R /mosquitto/log